title: Talent and Workforce Management Handbook
description: A Comprehensive Guide to ITIL/ITSM Workforce and Talent Management Best Practices
baseurl: "/TalentAndWorkforceManagementHandbook"
url: "https://zettai-seigi.github.io"
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: light

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/zettai-seigi/TalentAndWorkforceManagementHandbook"
  "English":
    - "/TalentAndWorkforceManagementHandbook/"
  "Indonesia":
    - "/TalentAndWorkforceManagementHandbook/id/"
aux_links_new_tab: false

# Footer
footer_content: "Copyright &copy; 2024. Distributed under the MIT License."

# Search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Navigation
nav_sort: case_insensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-remote-theme
